language: java
jdk: oraclejdk8
services:
- docker
script:
- "./gradlew check --info"
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    - SPRING_PROFILES_ACTIVE=default,integration-tests
branches:
  only:
  - master
notifications:
  slack:
    secure: gwaAvSUbGYRzIkkdWrfyacjcUfaW5RAnUDmzHCr8KDrXYDl00bANsCo7miNw2l9GnSp4JXc70Pokaya7LSOhO+YY3r1iaI5dpt9vkL5oqcxz7/qXtH2hHB7idJNUSHsgQhcX1q3eP7HFPrRf3CLtbqIL4zbNpRJkBoy9qgPiRkoVhXQ1wasHExiFaJQ0pbblu6E0XQGa7cJqJic7gVmY94iyFO1N4D5pTOLTxAkY/TxS5ESrkvLf/T5T08LTyClTsuRhrzC3e9nFzETRwisoP/tcFnTX38iJ4sTS5NRFTzhNnzrbJpu3SjUZ81FbIgNO4gGBkm7PA5G1MG258O0am3jxGwNpggIle7YJAQ/m3ZAZWCnfRA52avHEOj1Jt5NQpnXHumTOVLFgvQ0CfITitmpOG01K5vs++JJ/9prCLj0R9RzmRd/YWZWclk0EcYvhTq+oFTollY2kMaUORKSis1i7CkcN1l4kvV2A37lFq0JC29xYRsxhs+1gJsDlCh8dcWx/HisTG7XHw5dFqiQEOMXhS4NwFKJXe9BVkqL3VdaY1WnLzAWT54pHFDjfIC6VoYAwT4pVTDvz2rARMf+uc/64bz7wHtMgy7GUEbjX3QIxAwXNUBWFJCnax0RGhbQvWBFL3vZZmCt2RP029NUdP1F7nnYzy+YDXIvUltXWBow=
